name: Pull request closed
on:
  pull_request:
    types: [closed]

jobs:
  delete_qa:
    name: Delete Firebase Hosting preview (QA)
    runs-on: 'ubuntu-latest'
    steps:
      - name: Delete Firebase Hosting channel
      - uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:delete 'pull-request-${{ github.event.pull_request.number }}'
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKS_OUREAPP }}'
