name: Build, Test & Deploy Prod
on:
  release:
    types: [published]

jobs:
  build:
    name: Build frontend
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: frontend-preprod
          path: build

  test:
    name: Test frontend
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Test app
        run: yarn test
      # todo : add code coverage reports

  deploy_qa:
    name: Deploy to Firebase Hosting live (Prod)
    runs-on: 'ubuntu-latest'
    needs: [build, test]
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}' # exclude PR from forks
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: frontend-preprod

      - name: Deploy to Prod
        uses: w9jds/firebase-action@master
        with:
          args: hosting:clone ${{ secrets.FIREBASE_ID }}:preprod ${{ secrets.FIREBASE_ID }}:live
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKS_OUREAPP }}'