name: Build, Test, Deploy Preprod
on:
  release:
    types: [published]

env:
  NODE_VERSION: '16'
  RUNS_ON: 'ubuntu-latest'
  PREPROD_ID: 'preprod'

jobs:
  setup:
    name: Setup Pipeline
    runs-on: ${{ env.RUNS_ON}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - run: yarn install
          
  build:
    name: Build frontend
    runs-on: ${{ env.RUNS_ON}}
    needs: setup
    steps:
      - run: yarn build

  test:
    name: Test frontend
    runs-on: ${{ env.RUNS_ON}}
    needs: [setup, build]
    steps:
      - run: yarn test
      # todo : add code coverage reports

  preview:
    name: Deploy to Firebase Hosting preview (Preprod)
    runs-on: ${{ env.RUNS_ON}}
    needs: [setup, build, test]
    steps:
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKS_OUREAPP }}'
          projectId: '${{ secrets.FIREBASE_ID }}'
          channelId: ${{ env.PREPROD_ID }}
          expires: 100d
