name: Build, Test, Deploy Prod
on:
  release:
    types: [published]

jobs:
  setup:
    name: Setup Pipeline
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
          
  build:
    name: Build frontend
    runs-on: 'ubuntu-latest'
    needs: setup
    steps:
      - run: yarn build

  test:
    name: Test frontend
    runs-on: 'ubuntu-latest'
    needs: [setup, build]
    steps:
      - run: yarn test
      # todo : add code coverage reports

  preview:
    name: Deploy to Firebase Hosting live (Prod)
    runs-on: 'ubuntu-latest'
    needs: [setup, build, test]
    steps:
      - uses: w9jds/firebase-action@master
        with:
          args: hosting:clone ${{ secrets.FIREBASE_ID }}:preprod ${{ secrets.FIREBASE_ID }}:live
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKS_OUREAPP }}'
